# ==============================================================================
# ORDERS SERVICE
# Production Environment Overrides
# ==============================================================================

replicaCount: 1

image:
  repository: 162663626265.dkr.ecr.us-east-1.amazonaws.com/retail-store-v2/orders
  pullPolicy: IfNotPresent
  tag: "sha-7f8f55d"

app:
  persistence:
    provider: postgres
    database: ordersdb

    secret:
      name: orders-db

messaging:
  provider: sqs

  sqs:
    topic: prod-orders-queue

database:
  endpoint: prod-orders-postgresql.cifguuuaskpf.us-east-1.rds.amazonaws.com
  port: 5432
  serviceName: orders-postgres

secrets:
  awsRegion: us-east-1
  secretName: production/orders/database
  secretProviderClass: orders-db-secrets
