# ==============================================================================
# CATALOG SERVICE
# Production Environment Overrides
# ==============================================================================

replicaCount: 1

image:
  repository: 162663626265.dkr.ecr.us-east-1.amazonaws.com/retail-store-v2/catalog
  pullPolicy: IfNotPresent
  tag: "sha-49efebb"

app:
  persistence:
    provider: mysql
    database: catalogdb

    secret:
      name: catalog-db

database:
  endpoint: production-catalog-mysql.cifguuuaskpf.us-east-1.rds.amazonaws.com
  port: 3306
  serviceName: catalog-mysql

secrets:
  awsRegion: us-east-1
  secretName: production/catalog/database
  secretProviderClass: catalog-db-secrets