# ==============================================================================
# CHECKOUT SERVICE
# Production Environment Overrides
# ==============================================================================

image:
  repository: 162663626265.dkr.ecr.us-east-1.amazonaws.com/retail-store-v2/checkout
  pullPolicy: IfNotPresent
  tag: "sha-c8db3c7"

app:
  persistence:
    provider: redis
    redisUrl: "redis://prod-checkout-redis.m7f8mc.0001.use1.cache.amazonaws.com:6379"

  endpoints:
    orders: http://orders
